#!/bin/sh
# build-apk.sh - Build luci-app-fancontrol as an OpenWrt 25+ APK package
# Requires: apk-tools v2+, tar, gzip
# On OpenWrt 25: opkg install apk-tools  (or it's pre-installed)
# On Alpine/Debian: apk add alpine-sdk  /  apt install apk-tools

set -e

PKG="luci-app-fancontrol"
VER="2.3.0"
REL="0"
ARCH="all"
OUT="${PKG}-${VER}-r${REL}.apk"
BUILDDATE=$(date +%s)

echo "Building ${OUT}..."

WORK=$(mktemp -d)
DATADIR="$WORK/data"
CTRLDIR="$WORK/control"
mkdir -p "$DATADIR" "$CTRLDIR"

# ── Install package files into DATADIR ──────────────────────────────────────

install -Dm644 www/luci-static/resources/view/fancontrol/fancontrol.js \
  "$DATADIR/www/luci-static/resources/view/fancontrol/fancontrol.js"

install -Dm644 usr/share/luci/menu.d/luci-app-fancontrol.json \
  "$DATADIR/usr/share/luci/menu.d/luci-app-fancontrol.json"

install -Dm755 usr/libexec/rpcd/luci.fancontrol \
  "$DATADIR/usr/libexec/rpcd/luci.fancontrol"

install -Dm644 usr/share/rpcd/acl.d/luci-app-fancontrol.json \
  "$DATADIR/usr/share/rpcd/acl.d/luci-app-fancontrol.json"

install -Dm755 usr/bin/fancontrol_loop \
  "$DATADIR/usr/bin/fancontrol_loop"

install -Dm755 etc/init.d/fancontrol \
  "$DATADIR/etc/init.d/fancontrol"

install -Dm644 etc/fancontrol/fancontrol.conf \
  "$DATADIR/etc/fancontrol/fancontrol.conf"

# ── Calculate installed size ─────────────────────────────────────────────────

SIZE=$(du -sb "$DATADIR" 2>/dev/null | cut -f1 || du -sk "$DATADIR" | awk '{print $1 * 1024}')

# ── Build data.tar.gz ────────────────────────────────────────────────────────

tar czf "$WORK/data.tar.gz" \
  --owner=0 --group=0 --numeric-owner \
  -C "$DATADIR" .

# ── Write .PKGINFO ───────────────────────────────────────────────────────────

DATAHASH=$(sha256sum "$WORK/data.tar.gz" | cut -d' ' -f1)

cat > "$CTRLDIR/.PKGINFO" << EOF
# Generated by build-apk.sh
pkgname = $PKG
pkgver = ${VER}-r${REL}
arch = $ARCH
size = $SIZE
pkgdesc = Automatic PWM fan control with LuCI web interface
url = https://github.com/YOUR_USERNAME/luci-app-fancontrol
builddate = $BUILDDATE
packager = Custom Build
license = MIT
depend = luci-base
depend = rpcd
depend = jsonfilter
depend = kmod-hwmon-core
depend = kmod-hwmon-pwmfan
depend = kmod-i2c-core
depend = lm-sensors
datahash = $DATAHASH
EOF

# ── Write install scripts into control ───────────────────────────────────────

cat > "$CTRLDIR/.post-install" << 'SCRIPT'
#!/bin/sh
[ -f /etc/init.d/fancontrol ] && /etc/init.d/fancontrol enable && /etc/init.d/fancontrol start
[ -f /etc/init.d/rpcd ] && /etc/init.d/rpcd restart
SCRIPT

cat > "$CTRLDIR/.pre-deinstall" << 'SCRIPT'
#!/bin/sh
[ -f /etc/init.d/fancontrol ] && /etc/init.d/fancontrol stop && /etc/init.d/fancontrol disable
[ -f /etc/init.d/rpcd ] && /etc/init.d/rpcd restart
SCRIPT

chmod 755 "$CTRLDIR/.post-install" "$CTRLDIR/.pre-deinstall"

# ── Build control.tar.gz ─────────────────────────────────────────────────────

tar czf "$WORK/control.tar.gz" \
  --owner=0 --group=0 --numeric-owner \
  -C "$CTRLDIR" .

# ── Concatenate control + data into final .apk ───────────────────────────────
# APK v2 format: control.tar.gz concatenated with data.tar.gz
# (signature segment is prepended by abuild-sign; omitted here for untrusted install)

cat "$WORK/control.tar.gz" "$WORK/data.tar.gz" > "$OUT"

rm -rf "$WORK"

echo ""
echo "Built: $OUT ($(du -h $OUT | cut -f1))"
echo ""
echo "Install on OpenWrt 25+:"
echo "  scp $OUT root@192.168.1.1:/tmp/"
echo "  apk add --allow-untrusted /tmp/$OUT"
