#!/bin/sh
# build-apk.sh - Build luci-app-fancontrol as an OpenWrt 25+ / Alpine APK v2 package
#
# APK v2 format: a single tar archive split across three concatenated gzip streams:
#   stream 1: signature  (skipped here - use --allow-untrusted to install)
#   stream 2: control    (.PKGINFO + install scripts)
#   stream 3: data       (package files)
#
# Install on OpenWrt 25+:
#   apk add --allow-untrusted /tmp/luci-app-fancontrol-2.3.0-r0.apk

set -e

PKG="luci-app-fancontrol"
VER="2.3.0"
REL="0"
ARCH="all"
OUT="${PKG}-${VER}-r${REL}.apk"
BUILDDATE=$(date +%s)

echo "Building ${OUT}..."

WORK=$(mktemp -d)
trap "rm -rf $WORK" EXIT

DATADIR="$WORK/data"
CTRLDIR="$WORK/ctrl"
mkdir -p "$DATADIR" "$CTRLDIR"

# ── Install package files ────────────────────────────────────────────────────

install -Dm644 www/luci-static/resources/view/fancontrol/fancontrol.js \
  "$DATADIR/www/luci-static/resources/view/fancontrol/fancontrol.js"

install -Dm644 usr/share/luci/menu.d/luci-app-fancontrol.json \
  "$DATADIR/usr/share/luci/menu.d/luci-app-fancontrol.json"

install -Dm755 usr/libexec/rpcd/luci.fancontrol \
  "$DATADIR/usr/libexec/rpcd/luci.fancontrol"

install -Dm644 usr/share/rpcd/acl.d/luci-app-fancontrol.json \
  "$DATADIR/usr/share/rpcd/acl.d/luci-app-fancontrol.json"

install -Dm755 usr/bin/fancontrol_loop \
  "$DATADIR/usr/bin/fancontrol_loop"

install -Dm755 etc/init.d/fancontrol \
  "$DATADIR/etc/init.d/fancontrol"

install -Dm644 etc/fancontrol/fancontrol.conf \
  "$DATADIR/etc/fancontrol/fancontrol.conf"

# ── Build data stream (gzip stream 3) ────────────────────────────────────────

tar -czf "$WORK/stream-data.tar.gz" \
  --owner=0 --group=0 --numeric-owner \
  -C "$DATADIR" .

# ── Calculate data hash and installed size ───────────────────────────────────

DATAHASH=$(sha256sum "$WORK/stream-data.tar.gz" | cut -d' ' -f1)
SIZE=$(du -sk "$DATADIR" | awk '{print $1 * 1024}')

# ── Write .PKGINFO ───────────────────────────────────────────────────────────

cat > "$CTRLDIR/.PKGINFO" << EOF
# Generated by build-apk.sh
pkgname = $PKG
pkgver = ${VER}-r${REL}
arch = $ARCH
size = $SIZE
pkgdesc = Automatic PWM fan control with LuCI web interface
url = https://github.com/YOUR_USERNAME/luci-app-fancontrol
builddate = $BUILDDATE
packager = Custom Build
license = MIT
depend = luci-base
depend = rpcd
depend = jsonfilter
depend = kmod-hwmon-core
depend = kmod-hwmon-pwmfan
depend = kmod-i2c-core
depend = lm-sensors
datahash = $DATAHASH
EOF

# ── Write install scripts ─────────────────────────────────────────────────────

cat > "$CTRLDIR/.post-install" << 'EOF'
#!/bin/sh
[ -f /etc/init.d/fancontrol ] && /etc/init.d/fancontrol enable
[ -f /etc/init.d/fancontrol ] && /etc/init.d/fancontrol start
[ -f /etc/init.d/rpcd ] && /etc/init.d/rpcd restart
EOF

cat > "$CTRLDIR/.pre-deinstall" << 'EOF'
#!/bin/sh
[ -f /etc/init.d/fancontrol ] && /etc/init.d/fancontrol stop
[ -f /etc/init.d/fancontrol ] && /etc/init.d/fancontrol disable
[ -f /etc/init.d/rpcd ] && /etc/init.d/rpcd restart
EOF

chmod 755 "$CTRLDIR/.post-install" "$CTRLDIR/.pre-deinstall"

# ── Build control stream (gzip stream 2) ─────────────────────────────────────
# Must be a tar with .PKGINFO as first entry

tar -czf "$WORK/stream-ctrl.tar.gz" \
  --owner=0 --group=0 --numeric-owner \
  -C "$CTRLDIR" \
  .PKGINFO .post-install .pre-deinstall

# ── Assemble final APK ────────────────────────────────────────────────────────
# APK v2 = concatenated gzip streams (no signature stream = use --allow-untrusted)
# stream 2 (control) + stream 3 (data)

cat "$WORK/stream-ctrl.tar.gz" "$WORK/stream-data.tar.gz" > "$OUT"

echo ""
echo "Built: $OUT ($(du -h "$OUT" | cut -f1))"
echo ""
echo "Install on OpenWrt 25+:"
echo "  scp $OUT root@192.168.1.1:/tmp/"
echo "  apk add --allow-untrusted /tmp/$OUT"
