#!/bin/sh
[ "${IPKG_NO_SCRIPT}" = "1" ] && exit 0
# Migrate old shell key=value config to UCI format if present
if [ -f /etc/fancontrol/fancontrol.conf ]; then
  THERMAL="/sys/class/thermal/thermal_zone0/temp"
  PWM="/sys/class/hwmon/hwmon2/pwm1"
  TEMP_OFF=50; TEMP_HALF=65; TEMP_FULL=75; HYST=2; POLL=10
  . /etc/fancontrol/fancontrol.conf 2>/dev/null || true
  uci -q set fancontrol.settings=fancontrol
  uci -q set "fancontrol.settings.thermal=${THERMAL}"
  uci -q set "fancontrol.settings.pwm=${PWM}"
  uci -q set "fancontrol.settings.temp_off=${TEMP_OFF}"
  uci -q set "fancontrol.settings.temp_half=${TEMP_HALF}"
  uci -q set "fancontrol.settings.temp_full=${TEMP_FULL}"
  uci -q set "fancontrol.settings.hyst=${HYST}"
  uci -q set "fancontrol.settings.poll=${POLL}"
  uci -q commit fancontrol
  rm -f /etc/fancontrol/fancontrol.conf
  rmdir /etc/fancontrol 2>/dev/null || true
fi
/etc/init.d/fancontrol enable
/etc/init.d/fancontrol start
/etc/init.d/rpcd restart >/dev/null 2>&1
exit 0
